# extract
strava_request:
  auth_url: 'https://www.strava.com/oauth/token'
  activities_url: 'https://www.strava.com/api/v3/activities'
  request_params:
    access: {
      'client_id': "75389",
      'client_secret': 'ed536e7e4b34b7046c87c2ea4ab19d5b2916c82e',
      'refresh_token': 'a898970d810c84f649672e9dc8a6310f57763f0f',
      'grant_type': 'refresh_token',
      'f': 'json'
    }
    activity: {
      'include_all_efforts': False
    }
  request_limits:
    successive_calls: 80
    batch_size: 200 # limit is 200

db:
  extract:
    folder_path: './data_extract/db/'
    activities_file_name: 'strava_activities.pkl'
  transform:
    folder_path: './data_transform/db/'
    activities_file_name: 'activities.pkl'
    summary_file_name: 'summary.pkl'

# transform
activities_df_columns: ['id', 'name', 'distance', 'moving_time',
  'elapsed_time', 'total_elevation_gain', 'type', 'start_date',
  'average_speed', 'perceived_exertion', 'private_note']
average_speed_col_new_name: 'moving_speed'
body_parts_singular: ['cheville gauche', 'cheville droite', 'genou gauche',
  'genou droite', 'hanche gauche', 'hanche droite', 'cuisse gauche',
  'cuisse droite', 'mollet gauche', 'mollet droite', 'fessier gauche',
  'fessier droite']
body_parts_plural: ['chevilles', 'genoux', 'hanches', 'cuisses', 'mollets', 'fessiers']
summary:
  sports: ['Run', 'Ride']
  metrics: ['distance', 'elapsed_time', 'total_elevation_gain', 'load']
  column: 'type'
  row: 'month'
# notes_start_date: '10/09/2021'