strava_request:
  auth_url: 'https://www.strava.com/oauth/token'
  activities_url: 'https://www.strava.com/api/v3/activities'
  request_params:
    access: {
      'client_id': "75389",
      'client_secret': 'ed536e7e4b34b7046c87c2ea4ab19d5b2916c82e',
      'refresh_token': 'a898970d810c84f649672e9dc8a6310f57763f0f',
      'grant_type': 'refresh_token',
      'f': 'json'
    }
    activity: {
      'include_all_efforts': False
    }
  request_limits:
    successive_calls: 80
    batch_size: 200 # limit is 200

db:
  extract:
    folder_path: './data_extract/db/'
    activities_file_name: 'strava_activities.pkl'
  transform:
    folder_path: './data_transform/db/'
    activities_file_name: 'activities.pkl'
    injuries_file_name: 'injuries.pkl'
    summary_file_name: 'summary.pkl'
  plot:
    folder_path: './data_plot/plots/'
    summary_file_name: 'summary.pdf'
    correlations_file_name: 'correlations.pdf'
    factors_file_name: 'factors.pdf'
